<?php

namespace ArrowebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getReferences()
	{
		$qb = $this->createQueryBuilder('r')
			->orderBy('r.annee', 'DESC')
			->getQuery()
		;

		return $qb->getResult();
	}
}
